services:
  sona-rest:
    container_name: sona-rest
    hostname: sona-rest
    image: sona-rest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SRPING_SERVER_PORT: 8080
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@sona-mongo:27017/${MONGO_DATABASE}?authSource=admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://sona-db:5432/${DB_DATABASE}
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - sona-db
      - sona-mongo
    ports:
      - "8080:8080"
    volumes:
      - ./google:/opt/app/google
      - ./application.properties:/opt/app/application.properties

  sona-db:
    container_name: sona-db
    hostname: sona-db
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  sona-mongo:
    container_name: sona-mongo
    hostname: sona-mongo
    image: mongo:latest
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
      
networks:
  default:
    name: sona-network
