services:
  app:
    container_name: sona-app
    hostname: sona-app
    image: atenea-admin-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      environment:
      SPRING_APPLICATION_JSON: '{
          "server.port": 8080,
          "spring.datasource.driver-class-name": "org.postgresql.Driver",
          "spring.datasource.username": "${DB_USERNAME}",
          "spring.datasource.password": "${DB_PASSWORD}",
          "spring.datasource.url": "jdbc:postgresql://sona-db:5432/${DB_DATABASE}",
          "spring.jpa.database-platform": "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    depends_on:
      - db

  db:
    container_name: sona-db
    hostname: sona-db
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: postgres -c 'max_connections=1000'
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks:
  default:
    name: atenea-network
