services:
  sona-rest:
    container_name: sona-rest
    hostname: sona-rest
    image: sona-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      environment:
      SPRING_APPLICATION_JSON: '{
          "server.port": 8080,
          "spring.datasource.driver-class-name": "org.postgresql.Driver",
          "spring.datasource.username": "${DB_USERNAME}",
          "spring.datasource.password": "${DB_PASSWORD}",
          "spring.datasource.url": "jdbc:postgresql://sona-db:5432/${DB_DATABASE}",
          "spring.jpa.database-platform": "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update",
          "spring.jackson.serialization.write-dates-as-timestamps": false,
          "spring.data.mongodb.uri": "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@sona-mongo:27017/${MONGO_DATABASE}?authSource=admin"
        }'
    depends_on:
      - sona-db
      - sona-mongo

    ports:
      - "8080:8080"
    volumes:
      - ./google:/opt/app/google

  sona-db:
    container_name: sona-db
    hostname: sona-db
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: postgres -c 'max_connections=1000'
    ports:
      - "5435:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  sona-mongo:
    container_name: sona-mongo
    hostname: sona-mongo
    image: mongo:latest
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
      
networks:
  default:
    name: sona-network
